### ISSUE TITLE
Mono FastCGI package depends on mono-devel

### ISSUE THREAD

**Issue by junalmeida** [mono/linux-packaging-mono#27]
Is there a real need for a server package to depends on sdk tools like msbuild?

**Comment by akoeplinger** [comment]
I'd assume this is somehow related to the old System.Web-based ASP.NET needing the C# compiler to compile pages and this in turn pulls in mono-devel.

@directhex can confirm if that's the case.

**Comment by directhex** [comment]
Yes, that's the reasoning, System.Web needing mcs

**Comment by akoeplinger** [comment]
There you go :)

**Comment by junalmeida** [comment]
Ah ok, thank you :)
